version: '3'
services:
  web:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: digital-garden

